/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
<<<<<<< HEAD
export type { Pool } from './Pool'
=======
export type { FirstLossCover } from './FirstLossCover'
export type { Pool } from './Pool'
export type { PoolConfig } from './PoolConfig'
export type { PoolVault } from './PoolVault'
>>>>>>> cdafa93 (Page details (#61))
export type { TrancheVault } from './TrancheVault'
export * as factories from './factories'
export { FirstLossCover__factory } from './factories/FirstLossCover__factory'
export { Pool__factory } from './factories/Pool__factory'
<<<<<<< HEAD
=======
export { PoolConfig__factory } from './factories/PoolConfig__factory'
export { PoolVault__factory } from './factories/PoolVault__factory'
>>>>>>> cdafa93 (Page details (#61))
export { TrancheVault__factory } from './factories/TrancheVault__factory'
=======
export type { Pool } from "./Pool";
export type { PoolVault } from "./PoolVault";
export type { TrancheVault } from "./TrancheVault";
export * as factories from "./factories";
export { Pool__factory } from "./factories/Pool__factory";
export { PoolVault__factory } from "./factories/PoolVault__factory";
export { TrancheVault__factory } from "./factories/TrancheVault__factory";
>>>>>>> ff9b4d4 (Add local network (#46))
