/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export type ReceivableInputStruct = {
  receivableAmount: PromiseOrValue<BigNumberish>
  receivableId: PromiseOrValue<BigNumberish>
}

export type ReceivableInputStructOutput = [BigNumber, BigNumber] & {
  receivableAmount: BigNumber
  receivableId: BigNumber
}

export type CreditRecordStruct = {
  unbilledPrincipal: PromiseOrValue<BigNumberish>
  nextDueDate: PromiseOrValue<BigNumberish>
  nextDue: PromiseOrValue<BigNumberish>
  yieldDue: PromiseOrValue<BigNumberish>
  totalPastDue: PromiseOrValue<BigNumberish>
  missedPeriods: PromiseOrValue<BigNumberish>
  remainingPeriods: PromiseOrValue<BigNumberish>
  state: PromiseOrValue<BigNumberish>
}

export type CreditRecordStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  number,
  number,
  number,
] & {
  unbilledPrincipal: BigNumber
  nextDueDate: BigNumber
  nextDue: BigNumber
  yieldDue: BigNumber
  totalPastDue: BigNumber
  missedPeriods: number
  remainingPeriods: number
  state: number
}

export type DueDetailStruct = {
  lateFeeUpdatedDate: PromiseOrValue<BigNumberish>
  lateFee: PromiseOrValue<BigNumberish>
  principalPastDue: PromiseOrValue<BigNumberish>
  yieldPastDue: PromiseOrValue<BigNumberish>
  committed: PromiseOrValue<BigNumberish>
  accrued: PromiseOrValue<BigNumberish>
  paid: PromiseOrValue<BigNumberish>
}

export type DueDetailStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
] & {
  lateFeeUpdatedDate: BigNumber
  lateFee: BigNumber
  principalPastDue: BigNumber
  yieldPastDue: BigNumber
  committed: BigNumber
  accrued: BigNumber
  paid: BigNumber
}

export interface ReceivableBackedCreditLineInterface extends utils.Interface {
  functions: {
    'calendar()': FunctionFragment
    'creditManager()': FunctionFragment
    'drawdownWithReceivable(address,(uint96,uint64),uint256)': FunctionFragment
    'dueManager()': FunctionFragment
    'firstLossCover()': FunctionFragment
    'getCreditRecord(bytes32)': FunctionFragment
    'getDueDetail(bytes32)': FunctionFragment
    'getDueInfo(address)': FunctionFragment
    'getNextBillRefreshDate(address)': FunctionFragment
    'humaConfig()': FunctionFragment
    'initialize(address)': FunctionFragment
    'makePaymentWithReceivable(address,uint256,uint256)': FunctionFragment
    'makePrincipalPaymentAndDrawdownWithReceivable(address,uint256,uint256,(uint96,uint64),uint256)': FunctionFragment
    'makePrincipalPaymentWithReceivable(address,uint256,uint256)': FunctionFragment
    'onERC721Received(address,address,uint256,bytes)': FunctionFragment
    'poolConfig()': FunctionFragment
    'poolSafe()': FunctionFragment
    'setCreditRecord(bytes32,(uint96,uint64,uint96,uint96,uint96,uint16,uint16,uint8))': FunctionFragment
    'setPoolConfig(address)': FunctionFragment
    'updateDueInfo(bytes32,(uint96,uint64,uint96,uint96,uint96,uint16,uint16,uint8),(uint64,uint96,uint96,uint96,uint96,uint96,uint96))': FunctionFragment
    'updatePoolConfigData()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'calendar'
      | 'creditManager'
      | 'drawdownWithReceivable'
      | 'dueManager'
      | 'firstLossCover'
      | 'getCreditRecord'
      | 'getDueDetail'
      | 'getDueInfo'
      | 'getNextBillRefreshDate'
      | 'humaConfig'
      | 'initialize'
      | 'makePaymentWithReceivable'
      | 'makePrincipalPaymentAndDrawdownWithReceivable'
      | 'makePrincipalPaymentWithReceivable'
      | 'onERC721Received'
      | 'poolConfig'
      | 'poolSafe'
      | 'setCreditRecord'
      | 'setPoolConfig'
      | 'updateDueInfo'
      | 'updatePoolConfigData',
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'calendar', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'creditManager',
    values?: undefined,
  ): string
  encodeFunctionData(
    functionFragment: 'drawdownWithReceivable',
    values: [
      PromiseOrValue<string>,
      ReceivableInputStruct,
      PromiseOrValue<BigNumberish>,
    ],
  ): string
  encodeFunctionData(functionFragment: 'dueManager', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'firstLossCover',
    values?: undefined,
  ): string
  encodeFunctionData(
    functionFragment: 'getCreditRecord',
    values: [PromiseOrValue<BytesLike>],
  ): string
  encodeFunctionData(
    functionFragment: 'getDueDetail',
    values: [PromiseOrValue<BytesLike>],
  ): string
  encodeFunctionData(
    functionFragment: 'getDueInfo',
    values: [PromiseOrValue<string>],
  ): string
  encodeFunctionData(
    functionFragment: 'getNextBillRefreshDate',
    values: [PromiseOrValue<string>],
  ): string
  encodeFunctionData(functionFragment: 'humaConfig', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [PromiseOrValue<string>],
  ): string
  encodeFunctionData(
    functionFragment: 'makePaymentWithReceivable',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
    ],
  ): string
  encodeFunctionData(
    functionFragment: 'makePrincipalPaymentAndDrawdownWithReceivable',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      ReceivableInputStruct,
      PromiseOrValue<BigNumberish>,
    ],
  ): string
  encodeFunctionData(
    functionFragment: 'makePrincipalPaymentWithReceivable',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
    ],
  ): string
  encodeFunctionData(
    functionFragment: 'onERC721Received',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
    ],
  ): string
  encodeFunctionData(functionFragment: 'poolConfig', values?: undefined): string
  encodeFunctionData(functionFragment: 'poolSafe', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'setCreditRecord',
    values: [PromiseOrValue<BytesLike>, CreditRecordStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'setPoolConfig',
    values: [PromiseOrValue<string>],
  ): string
  encodeFunctionData(
    functionFragment: 'updateDueInfo',
    values: [PromiseOrValue<BytesLike>, CreditRecordStruct, DueDetailStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'updatePoolConfigData',
    values?: undefined,
  ): string

  decodeFunctionResult(functionFragment: 'calendar', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'creditManager',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'drawdownWithReceivable',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'dueManager', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'firstLossCover',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getCreditRecord',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getDueDetail',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'getDueInfo', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getNextBillRefreshDate',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'humaConfig', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'makePaymentWithReceivable',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'makePrincipalPaymentAndDrawdownWithReceivable',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'makePrincipalPaymentWithReceivable',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC721Received',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'poolConfig', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolSafe', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'setCreditRecord',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'setPoolConfig',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'updateDueInfo',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'updatePoolConfigData',
    data: BytesLike,
  ): Result

  events: {
    'BillRefreshed(bytes32,uint256,uint256)': EventFragment
    'CreditClosedAfterPayOff(bytes32,address)': EventFragment
    'CreditInitiated(address,uint256,uint256,uint8,uint256,bool)': EventFragment
    'CreditLineChanged(address,uint256,uint256)': EventFragment
    'DrawdownMade(address,uint256,uint256)': EventFragment
    'DrawdownMadeWithReceivable(address,uint256,uint256,uint256,address)': EventFragment
    'Initialized(uint8)': EventFragment
    'PaymentMade(address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,address)': EventFragment
    'PaymentMadeWithReceivable(address,uint256,uint256,address)': EventFragment
    'PoolConfigCacheUpdated(address)': EventFragment
    'PoolConfigChanged(address,address)': EventFragment
    'PrincipalPaymentMade(address,address,uint256,uint256,uint256,uint256,uint256,uint256,address)': EventFragment
    'PrincipalPaymentMadeWithReceivable(address,uint256,uint256,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'BillRefreshed'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CreditClosedAfterPayOff'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CreditInitiated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CreditLineChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'DrawdownMade'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'DrawdownMadeWithReceivable'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PaymentMade'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PaymentMadeWithReceivable'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PoolConfigCacheUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PoolConfigChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PrincipalPaymentMade'): EventFragment
  getEvent(
    nameOrSignatureOrTopic: 'PrincipalPaymentMadeWithReceivable',
  ): EventFragment
}

export interface BillRefreshedEventObject {
  creditHash: string
  newDueDate: BigNumber
  amountDue: BigNumber
}
export type BillRefreshedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  BillRefreshedEventObject
>

export type BillRefreshedEventFilter = TypedEventFilter<BillRefreshedEvent>

export interface CreditClosedAfterPayOffEventObject {
  creditHash: string
  by: string
}
export type CreditClosedAfterPayOffEvent = TypedEvent<
  [string, string],
  CreditClosedAfterPayOffEventObject
>

export type CreditClosedAfterPayOffEventFilter =
  TypedEventFilter<CreditClosedAfterPayOffEvent>

export interface CreditInitiatedEventObject {
  borrower: string
  creditLimit: BigNumber
  aprInBps: BigNumber
  periodDuration: number
  remainingPeriods: BigNumber
  approved: boolean
}
export type CreditInitiatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, number, BigNumber, boolean],
  CreditInitiatedEventObject
>

export type CreditInitiatedEventFilter = TypedEventFilter<CreditInitiatedEvent>

export interface CreditLineChangedEventObject {
  borrower: string
  oldCreditLimit: BigNumber
  newCreditLimit: BigNumber
}
export type CreditLineChangedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  CreditLineChangedEventObject
>

export type CreditLineChangedEventFilter =
  TypedEventFilter<CreditLineChangedEvent>

export interface DrawdownMadeEventObject {
  borrower: string
  borrowAmount: BigNumber
  netAmountToBorrower: BigNumber
}
export type DrawdownMadeEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  DrawdownMadeEventObject
>

export type DrawdownMadeEventFilter = TypedEventFilter<DrawdownMadeEvent>

export interface DrawdownMadeWithReceivableEventObject {
  borrower: string
  receivableId: BigNumber
  receivableAmount: BigNumber
  amount: BigNumber
  by: string
}
export type DrawdownMadeWithReceivableEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string],
  DrawdownMadeWithReceivableEventObject
>

export type DrawdownMadeWithReceivableEventFilter =
  TypedEventFilter<DrawdownMadeWithReceivableEvent>

export interface InitializedEventObject {
  version: number
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>

export interface PaymentMadeEventObject {
  borrower: string
  payer: string
  amount: BigNumber
  yieldDuePaid: BigNumber
  principalDuePaid: BigNumber
  unbilledPrincipalPaid: BigNumber
  yieldPastDuePaid: BigNumber
  lateFeePaid: BigNumber
  principalPastDuePaid: BigNumber
  by: string
}
export type PaymentMadeEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
  ],
  PaymentMadeEventObject
>

export type PaymentMadeEventFilter = TypedEventFilter<PaymentMadeEvent>

export interface PaymentMadeWithReceivableEventObject {
  borrower: string
  receivableId: BigNumber
  amount: BigNumber
  by: string
}
export type PaymentMadeWithReceivableEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  PaymentMadeWithReceivableEventObject
>

export type PaymentMadeWithReceivableEventFilter =
  TypedEventFilter<PaymentMadeWithReceivableEvent>

export interface PoolConfigCacheUpdatedEventObject {
  poolConfig: string
}
export type PoolConfigCacheUpdatedEvent = TypedEvent<
  [string],
  PoolConfigCacheUpdatedEventObject
>

export type PoolConfigCacheUpdatedEventFilter =
  TypedEventFilter<PoolConfigCacheUpdatedEvent>

export interface PoolConfigChangedEventObject {
  newPoolConfig: string
  oldPoolConfig: string
}
export type PoolConfigChangedEvent = TypedEvent<
  [string, string],
  PoolConfigChangedEventObject
>

export type PoolConfigChangedEventFilter =
  TypedEventFilter<PoolConfigChangedEvent>

export interface PrincipalPaymentMadeEventObject {
  borrower: string
  payer: string
  amount: BigNumber
  nextDueDate: BigNumber
  principalDue: BigNumber
  unbilledPrincipal: BigNumber
  principalDuePaid: BigNumber
  unbilledPrincipalPaid: BigNumber
  by: string
}
export type PrincipalPaymentMadeEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
  ],
  PrincipalPaymentMadeEventObject
>

export type PrincipalPaymentMadeEventFilter =
  TypedEventFilter<PrincipalPaymentMadeEvent>

export interface PrincipalPaymentMadeWithReceivableEventObject {
  borrower: string
  receivableId: BigNumber
  amount: BigNumber
  by: string
}
export type PrincipalPaymentMadeWithReceivableEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  PrincipalPaymentMadeWithReceivableEventObject
>

export type PrincipalPaymentMadeWithReceivableEventFilter =
  TypedEventFilter<PrincipalPaymentMadeWithReceivableEvent>

export interface ReceivableBackedCreditLine extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: ReceivableBackedCreditLineInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    calendar(overrides?: CallOverrides): Promise<[string]>

    creditManager(overrides?: CallOverrides): Promise<[string]>

    drawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableInput: ReceivableInputStruct,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    dueManager(overrides?: CallOverrides): Promise<[string]>

    firstLossCover(overrides?: CallOverrides): Promise<[string]>

    getCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<[CreditRecordStructOutput]>

    getDueDetail(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<[DueDetailStructOutput]>

    getDueInfo(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<
      [CreditRecordStructOutput, DueDetailStructOutput] & {
        cr: CreditRecordStructOutput
        dd: DueDetailStructOutput
      }
    >

    getNextBillRefreshDate(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { refreshDate: BigNumber }>

    humaConfig(overrides?: CallOverrides): Promise<[string]>

    initialize(
      _poolConfig: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    makePaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    makePrincipalPaymentAndDrawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      paymentReceivableId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      drawdownReceivableInput: ReceivableInputStruct,
      drawdownAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    makePrincipalPaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    poolConfig(overrides?: CallOverrides): Promise<[string]>

    poolSafe(overrides?: CallOverrides): Promise<[string]>

    setCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    setPoolConfig(
      _poolConfig: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    updateDueInfo(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      dd: DueDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    updatePoolConfigData(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>
  }

  calendar(overrides?: CallOverrides): Promise<string>

  creditManager(overrides?: CallOverrides): Promise<string>

  drawdownWithReceivable(
    borrower: PromiseOrValue<string>,
    receivableInput: ReceivableInputStruct,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  dueManager(overrides?: CallOverrides): Promise<string>

  firstLossCover(overrides?: CallOverrides): Promise<string>

  getCreditRecord(
    creditHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides,
  ): Promise<CreditRecordStructOutput>

  getDueDetail(
    creditHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides,
  ): Promise<DueDetailStructOutput>

  getDueInfo(
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<
    [CreditRecordStructOutput, DueDetailStructOutput] & {
      cr: CreditRecordStructOutput
      dd: DueDetailStructOutput
    }
  >

  getNextBillRefreshDate(
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>

  humaConfig(overrides?: CallOverrides): Promise<string>

  initialize(
    _poolConfig: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  makePaymentWithReceivable(
    borrower: PromiseOrValue<string>,
    receivableId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  makePrincipalPaymentAndDrawdownWithReceivable(
    borrower: PromiseOrValue<string>,
    paymentReceivableId: PromiseOrValue<BigNumberish>,
    paymentAmount: PromiseOrValue<BigNumberish>,
    drawdownReceivableInput: ReceivableInputStruct,
    drawdownAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  makePrincipalPaymentWithReceivable(
    borrower: PromiseOrValue<string>,
    receivableId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  poolConfig(overrides?: CallOverrides): Promise<string>

  poolSafe(overrides?: CallOverrides): Promise<string>

  setCreditRecord(
    creditHash: PromiseOrValue<BytesLike>,
    cr: CreditRecordStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  setPoolConfig(
    _poolConfig: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  updateDueInfo(
    creditHash: PromiseOrValue<BytesLike>,
    cr: CreditRecordStruct,
    dd: DueDetailStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  updatePoolConfigData(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  callStatic: {
    calendar(overrides?: CallOverrides): Promise<string>

    creditManager(overrides?: CallOverrides): Promise<string>

    drawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableInput: ReceivableInputStruct,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>

    dueManager(overrides?: CallOverrides): Promise<string>

    firstLossCover(overrides?: CallOverrides): Promise<string>

    getCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<CreditRecordStructOutput>

    getDueDetail(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<DueDetailStructOutput>

    getDueInfo(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<
      [CreditRecordStructOutput, DueDetailStructOutput] & {
        cr: CreditRecordStructOutput
        dd: DueDetailStructOutput
      }
    >

    getNextBillRefreshDate(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    humaConfig(overrides?: CallOverrides): Promise<string>

    initialize(
      _poolConfig: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>

    makePaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [BigNumber, boolean] & { amountPaid: BigNumber; paidoff: boolean }
    >

    makePrincipalPaymentAndDrawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      paymentReceivableId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      drawdownReceivableInput: ReceivableInputStruct,
      drawdownAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [BigNumber, boolean] & { amountPaid: BigNumber; paidoff: boolean }
    >

    makePrincipalPaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [BigNumber, boolean] & { amountPaid: BigNumber; paidoff: boolean }
    >

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<string>

    poolConfig(overrides?: CallOverrides): Promise<string>

    poolSafe(overrides?: CallOverrides): Promise<string>

    setCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      overrides?: CallOverrides,
    ): Promise<void>

    setPoolConfig(
      _poolConfig: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>

    updateDueInfo(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      dd: DueDetailStruct,
      overrides?: CallOverrides,
    ): Promise<void>

    updatePoolConfigData(overrides?: CallOverrides): Promise<void>
  }

  filters: {
    'BillRefreshed(bytes32,uint256,uint256)'(
      creditHash?: PromiseOrValue<BytesLike> | null,
      newDueDate?: null,
      amountDue?: null,
    ): BillRefreshedEventFilter
    BillRefreshed(
      creditHash?: PromiseOrValue<BytesLike> | null,
      newDueDate?: null,
      amountDue?: null,
    ): BillRefreshedEventFilter

    'CreditClosedAfterPayOff(bytes32,address)'(
      creditHash?: PromiseOrValue<BytesLike> | null,
      by?: null,
    ): CreditClosedAfterPayOffEventFilter
    CreditClosedAfterPayOff(
      creditHash?: PromiseOrValue<BytesLike> | null,
      by?: null,
    ): CreditClosedAfterPayOffEventFilter

    'CreditInitiated(address,uint256,uint256,uint8,uint256,bool)'(
      borrower?: PromiseOrValue<string> | null,
      creditLimit?: null,
      aprInBps?: null,
      periodDuration?: null,
      remainingPeriods?: null,
      approved?: null,
    ): CreditInitiatedEventFilter
    CreditInitiated(
      borrower?: PromiseOrValue<string> | null,
      creditLimit?: null,
      aprInBps?: null,
      periodDuration?: null,
      remainingPeriods?: null,
      approved?: null,
    ): CreditInitiatedEventFilter

    'CreditLineChanged(address,uint256,uint256)'(
      borrower?: PromiseOrValue<string> | null,
      oldCreditLimit?: null,
      newCreditLimit?: null,
    ): CreditLineChangedEventFilter
    CreditLineChanged(
      borrower?: PromiseOrValue<string> | null,
      oldCreditLimit?: null,
      newCreditLimit?: null,
    ): CreditLineChangedEventFilter

    'DrawdownMade(address,uint256,uint256)'(
      borrower?: PromiseOrValue<string> | null,
      borrowAmount?: null,
      netAmountToBorrower?: null,
    ): DrawdownMadeEventFilter
    DrawdownMade(
      borrower?: PromiseOrValue<string> | null,
      borrowAmount?: null,
      netAmountToBorrower?: null,
    ): DrawdownMadeEventFilter

    'DrawdownMadeWithReceivable(address,uint256,uint256,uint256,address)'(
      borrower?: PromiseOrValue<string> | null,
      receivableId?: PromiseOrValue<BigNumberish> | null,
      receivableAmount?: null,
      amount?: null,
      by?: null,
    ): DrawdownMadeWithReceivableEventFilter
    DrawdownMadeWithReceivable(
      borrower?: PromiseOrValue<string> | null,
      receivableId?: PromiseOrValue<BigNumberish> | null,
      receivableAmount?: null,
      amount?: null,
      by?: null,
    ): DrawdownMadeWithReceivableEventFilter

    'Initialized(uint8)'(version?: null): InitializedEventFilter
    Initialized(version?: null): InitializedEventFilter

    'PaymentMade(address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,address)'(
      borrower?: PromiseOrValue<string> | null,
      payer?: PromiseOrValue<string> | null,
      amount?: null,
      yieldDuePaid?: null,
      principalDuePaid?: null,
      unbilledPrincipalPaid?: null,
      yieldPastDuePaid?: null,
      lateFeePaid?: null,
      principalPastDuePaid?: null,
      by?: null,
    ): PaymentMadeEventFilter
    PaymentMade(
      borrower?: PromiseOrValue<string> | null,
      payer?: PromiseOrValue<string> | null,
      amount?: null,
      yieldDuePaid?: null,
      principalDuePaid?: null,
      unbilledPrincipalPaid?: null,
      yieldPastDuePaid?: null,
      lateFeePaid?: null,
      principalPastDuePaid?: null,
      by?: null,
    ): PaymentMadeEventFilter

    'PaymentMadeWithReceivable(address,uint256,uint256,address)'(
      borrower?: PromiseOrValue<string> | null,
      receivableId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      by?: null,
    ): PaymentMadeWithReceivableEventFilter
    PaymentMadeWithReceivable(
      borrower?: PromiseOrValue<string> | null,
      receivableId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      by?: null,
    ): PaymentMadeWithReceivableEventFilter

    'PoolConfigCacheUpdated(address)'(
      poolConfig?: PromiseOrValue<string> | null,
    ): PoolConfigCacheUpdatedEventFilter
    PoolConfigCacheUpdated(
      poolConfig?: PromiseOrValue<string> | null,
    ): PoolConfigCacheUpdatedEventFilter

    'PoolConfigChanged(address,address)'(
      newPoolConfig?: PromiseOrValue<string> | null,
      oldPoolConfig?: PromiseOrValue<string> | null,
    ): PoolConfigChangedEventFilter
    PoolConfigChanged(
      newPoolConfig?: PromiseOrValue<string> | null,
      oldPoolConfig?: PromiseOrValue<string> | null,
    ): PoolConfigChangedEventFilter

    'PrincipalPaymentMade(address,address,uint256,uint256,uint256,uint256,uint256,uint256,address)'(
      borrower?: PromiseOrValue<string> | null,
      payer?: PromiseOrValue<string> | null,
      amount?: null,
      nextDueDate?: null,
      principalDue?: null,
      unbilledPrincipal?: null,
      principalDuePaid?: null,
      unbilledPrincipalPaid?: null,
      by?: null,
    ): PrincipalPaymentMadeEventFilter
    PrincipalPaymentMade(
      borrower?: PromiseOrValue<string> | null,
      payer?: PromiseOrValue<string> | null,
      amount?: null,
      nextDueDate?: null,
      principalDue?: null,
      unbilledPrincipal?: null,
      principalDuePaid?: null,
      unbilledPrincipalPaid?: null,
      by?: null,
    ): PrincipalPaymentMadeEventFilter

    'PrincipalPaymentMadeWithReceivable(address,uint256,uint256,address)'(
      borrower?: PromiseOrValue<string> | null,
      receivableId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      by?: null,
    ): PrincipalPaymentMadeWithReceivableEventFilter
    PrincipalPaymentMadeWithReceivable(
      borrower?: PromiseOrValue<string> | null,
      receivableId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      by?: null,
    ): PrincipalPaymentMadeWithReceivableEventFilter
  }

  estimateGas: {
    calendar(overrides?: CallOverrides): Promise<BigNumber>

    creditManager(overrides?: CallOverrides): Promise<BigNumber>

    drawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableInput: ReceivableInputStruct,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    dueManager(overrides?: CallOverrides): Promise<BigNumber>

    firstLossCover(overrides?: CallOverrides): Promise<BigNumber>

    getCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getDueDetail(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getDueInfo(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getNextBillRefreshDate(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    humaConfig(overrides?: CallOverrides): Promise<BigNumber>

    initialize(
      _poolConfig: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    makePaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    makePrincipalPaymentAndDrawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      paymentReceivableId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      drawdownReceivableInput: ReceivableInputStruct,
      drawdownAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    makePrincipalPaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    poolConfig(overrides?: CallOverrides): Promise<BigNumber>

    poolSafe(overrides?: CallOverrides): Promise<BigNumber>

    setCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    setPoolConfig(
      _poolConfig: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    updateDueInfo(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      dd: DueDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    updatePoolConfigData(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>
  }

  populateTransaction: {
    calendar(overrides?: CallOverrides): Promise<PopulatedTransaction>

    creditManager(overrides?: CallOverrides): Promise<PopulatedTransaction>

    drawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableInput: ReceivableInputStruct,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    dueManager(overrides?: CallOverrides): Promise<PopulatedTransaction>

    firstLossCover(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getDueDetail(
      creditHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getDueInfo(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getNextBillRefreshDate(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    humaConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>

    initialize(
      _poolConfig: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    makePaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    makePrincipalPaymentAndDrawdownWithReceivable(
      borrower: PromiseOrValue<string>,
      paymentReceivableId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      drawdownReceivableInput: ReceivableInputStruct,
      drawdownAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    makePrincipalPaymentWithReceivable(
      borrower: PromiseOrValue<string>,
      receivableId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    poolConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>

    poolSafe(overrides?: CallOverrides): Promise<PopulatedTransaction>

    setCreditRecord(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    setPoolConfig(
      _poolConfig: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    updateDueInfo(
      creditHash: PromiseOrValue<BytesLike>,
      cr: CreditRecordStruct,
      dd: DueDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    updatePoolConfigData(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>
  }
}
