/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
export { Pool__factory } from './Pool__factory'
export { TrancheVault__factory } from './TrancheVault__factory'
=======
export { Pool__factory } from "./Pool__factory";
export { TrancheVault__factory } from "./TrancheVault__factory";
>>>>>>> ff9b4d4 (Add local network (#46))
