/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { PoolConfig, PoolConfigInterface } from '../PoolConfig'

const _abi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'creditLineTooHigh',
    type: 'error',
  },
  {
    inputs: [],
    name: 'evaluationAgentNotEnoughLiquidity',
    type: 'error',
  },
  {
    inputs: [],
    name: 'invalidBasisPointHigherThan10000',
    type: 'error',
  },
  {
    inputs: [],
    name: 'invalidCalendarUnit',
    type: 'error',
  },
  {
    inputs: [],
    name: 'lessThanRequiredCover',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notEpochManager',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notPool',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notPoolFeeManager',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notPoolOwner',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notPoolOwnerOrEA',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notPoolOwnerTreasury',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notPoolOwnerTreasuryOrEA',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notTrancheVault',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notTrancheVaultOrEpochManager',
    type: 'error',
  },
  {
    inputs: [],
    name: 'notTrancheVaultOrFirstLossCoverOrCreditOrPoolFeeManager',
    type: 'error',
  },
  {
    inputs: [],
    name: 'permissionDeniedNotAdmin',
    type: 'error',
  },
  {
    inputs: [],
    name: 'poolIsNotOn',
    type: 'error',
  },
  {
    inputs: [],
    name: 'poolOperatorRequired',
    type: 'error',
  },
  {
    inputs: [],
    name: 'poolOwnerNotEnoughLiquidity',
    type: 'error',
  },
  {
    inputs: [],
    name: 'proposedEADoesNotOwnProvidedEANFT',
    type: 'error',
  },
  {
    inputs: [],
    name: 'protocolIsPaused',
    type: 'error',
  },
  {
    inputs: [],
    name: 'underlyingTokenNotApprovedForHumaProtocol',
    type: 'error',
  },
  {
    inputs: [],
    name: 'zeroAddressProvided',
    type: 'error',
  },
  {
    inputs: [],
    name: 'zeroAmountProvided',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'advanceRateInBps',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'AdvanceRateInBpsChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'calendar',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'CalendarChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'durationInDays',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'CreditApprovalExpirationChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'credit',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'CreditChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'rewardsRate',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'liquidityRate',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'EARewardsAndLiquidityChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'epochManager',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'EpochManagerChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'oldEA',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newEA',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newEAId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'EvaluationAgentChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'EvaluationAgentRewardsWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint16',
        name: 'yieldInBps',
        type: 'uint16',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'minPrincipalRateInBps',
        type: 'uint16',
      },
      {
        indexed: false,
        internalType: 'uint96',
        name: 'lateFeeFlat',
        type: 'uint96',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'lateFeeBps',
        type: 'uint16',
      },
      {
        indexed: false,
        internalType: 'uint96',
        name: 'membershipFee',
        type: 'uint96',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'FeeStructureChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address[]',
        name: 'firstLossCovers',
        type: 'address[]',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'FirstLossCoversChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint96',
        name: 'frontLoadingFeeFlat',
        type: 'uint96',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'frontLoadingFeeBps',
        type: 'uint16',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'FrontLoadingFeesChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'humaConfig',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'HumaConfigChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint8',
        name: 'version',
        type: 'uint8',
      },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bool',
        name: 'permissioned',
        type: 'bool',
      },
      {
        indexed: false,
        internalType: 'uint96',
        name: 'liquidityCap',
        type: 'uint96',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'withdrawalLockoutInCalendarUnit',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'maxSeniorJuniorRatio',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'fixedSeniorYieldInBps',
        type: 'uint16',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'tranchesRiskAdjustmentInBps',
        type: 'uint16',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'LPConfigChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'gracePeriodInDays',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'LatePaymentGracePeriodChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'maxCreditLine',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'MaxCreditLineChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'pool',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'enum CalendarUnit',
        name: 'unit',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'gracePeriodInDays',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolDefaultGracePeriodChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'poolFeeManager',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolFeeManagerChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bool',
        name: 'enabled',
        type: 'bool',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'windowInEpoch',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolFlexCallChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'liquidityCap',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolLiquidityCapChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'string',
        name: 'name',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolNameChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'rewardsRate',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'liquidityRate',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolOwnerRewardsAndLiquidityChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'treasury',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolOwnerTreasuryChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'enum CalendarUnit',
        name: 'unit',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'number',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolPayPeriodChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'PoolRewardsWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'poolSafe',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolSafeChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'underlyingToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'PoolUnderlyingTokenChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'ProtocolRewardsWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'receivableAsset',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'ReceivableAssetChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'receivableRequiredInBps',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'ReceivableRequiredInBpsChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'previousAdminRole',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'newAdminRole',
        type: 'bytes32',
      },
    ],
    name: 'RoleAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'seniorTranche',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'juniorTranche',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'TranchesChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tranchesPolicy',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'TranchesPolicyChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'enum CalendarUnit',
        name: 'unit',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'lockoutPeriodInDays',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'WithdrawalLockoutPeriodChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'aprInBps',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'by',
        type: 'address',
      },
    ],
    name: 'YieldChanged',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'POOL_OPERATOR_ROLE',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'calendar',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'checkFirstLossCoverRequirementsForAdmin',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
    ],
    name: 'checkFirstLossCoverRequirementsForRedemption',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'balance',
        type: 'uint256',
      },
    ],
    name: 'checkLiquidityRequirementForEA',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'balance',
        type: 'uint256',
      },
    ],
    name: 'checkLiquidityRequirementForPoolOwner',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'trancheVault',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'newBalance',
        type: 'uint256',
      },
    ],
    name: 'checkLiquidityRequirementForRedemption',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'checkLiquidityRequirements',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'credit',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'creditFeeManager',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'creditPnLManager',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'epochManager',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'evaluationAgent',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'evaluationAgentId',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAdminRnR',
    outputs: [
      {
        components: [
          {
            internalType: 'uint16',
            name: 'rewardRateInBpsForEA',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'rewardRateInBpsForPoolOwner',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'liquidityRateInBpsByEA',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'liquidityRateInBpsByPoolOwner',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'rewardRateInBpsForPoolCover',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'liquidityRateInBpsByPoolCover',
            type: 'uint16',
          },
        ],
        internalType: 'struct AdminRnR',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFees',
    outputs: [
      {
        internalType: 'uint256',
        name: '_lateFeeFlat',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_lateFeeBps',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_membershipFee',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'index',
        type: 'uint256',
      },
    ],
    name: 'getFirstLossCover',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'firstLossCover',
        type: 'address',
      },
    ],
    name: 'getFirstLossCoverProfitEscrow',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFirstLossCovers',
    outputs: [
      {
        internalType: 'address[16]',
        name: '',
        type: 'address[16]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFrontLoadingFees',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLPConfig',
    outputs: [
      {
        components: [
          {
            internalType: 'bool',
            name: 'permissioned',
            type: 'bool',
          },
          {
            internalType: 'uint96',
            name: 'liquidityCap',
            type: 'uint96',
          },
          {
            internalType: 'uint8',
            name: 'withdrawalLockoutInCalendarUnit',
            type: 'uint8',
          },
          {
            internalType: 'uint8',
            name: 'maxSeniorJuniorRatio',
            type: 'uint8',
          },
          {
            internalType: 'uint16',
            name: 'fixedSeniorYieldInBps',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'tranchesRiskAdjustmentInBps',
            type: 'uint16',
          },
        ],
        internalType: 'struct LPConfig',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMinPrincipalRateInBps',
    outputs: [
      {
        internalType: 'uint256',
        name: '_minPrincipalRate',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPoolSettings',
    outputs: [
      {
        components: [
          {
            internalType: 'uint96',
            name: 'maxCreditLine',
            type: 'uint96',
          },
          {
            internalType: 'enum CalendarUnit',
            name: 'calendarUnit',
            type: 'uint8',
          },
          {
            internalType: 'uint8',
            name: 'payPeriodInCalendarUnit',
            type: 'uint8',
          },
          {
            internalType: 'uint16',
            name: 'creditApprovalExpirationInDays',
            type: 'uint16',
          },
          {
            internalType: 'uint8',
            name: 'latePaymentGracePeriodInDays',
            type: 'uint8',
          },
          {
            internalType: 'uint16',
            name: 'defaultGracePeriodInCalendarUnit',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'receivableRequiredInBps',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'advanceRateInBps',
            type: 'uint16',
          },
          {
            internalType: 'uint8',
            name: 'flexCallWindowInEpochs',
            type: 'uint8',
          },
          {
            internalType: 'bool',
            name: 'singleBorrower',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'singleCreditPerBorrower',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'flexCreditEnabled',
            type: 'bool',
          },
        ],
        internalType: 'struct PoolSettings',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPoolSummary',
    outputs: [
      {
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'yieldInBps',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'payPeriod',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxCreditAmount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'liquidityCap',
        type: 'uint256',
      },
      {
        internalType: 'string',
        name: 'name',
        type: 'string',
      },
      {
        internalType: 'string',
        name: 'symbol',
        type: 'string',
      },
      {
        internalType: 'uint8',
        name: 'decimals',
        type: 'uint8',
      },
      {
        internalType: 'uint256',
        name: 'eaId',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'eaNFTAddress',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRiskYieldMultipliers',
    outputs: [
      {
        internalType: 'uint16[16]',
        name: '',
        type: 'uint16[16]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
    ],
    name: 'getRoleAdmin',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'index',
        type: 'uint256',
      },
    ],
    name: 'getTrancheLiquidityCap',
    outputs: [
      {
        internalType: 'uint256',
        name: 'cap',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'hasRole',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'humaConfig',
    outputs: [
      {
        internalType: 'contract HumaConfig',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: '_poolName',
        type: 'string',
      },
      {
        internalType: 'address[]',
        name: '_contracts',
        type: 'address[]',
      },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'isPoolOwnerTreasuryOrEA',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'juniorTranche',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyEpochManager',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyOwnerOrHumaMasterAdmin',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPool',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPoolFeeManager',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPoolOperator',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPoolOwner',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPoolOwnerOrEA',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPoolOwnerTreasury',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyPoolOwnerTreasuryOrEA',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'onlyProtocolAndPoolOn',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'trancheVault',
        type: 'address',
      },
    ],
    name: 'onlyTrancheVault',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyTrancheVaultOrEpochManager',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'onlyTrancheVaultOrFirstLossCoverOrCreditOrPoolFeeManager',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pool',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poolFeeManager',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poolName',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poolOwnerTreasury',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poolSafe',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'receivableAsset',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'seniorTranche',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'advanceRateInBps',
        type: 'uint256',
      },
    ],
    name: 'setAdvanceRateInBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_calendar',
        type: 'address',
      },
    ],
    name: 'setCalendar',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_credit',
        type: 'address',
      },
    ],
    name: 'setCredit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'durationInDays',
        type: 'uint256',
      },
    ],
    name: 'setCreditApprovalExpiration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'rewardsRate',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'liquidityRate',
        type: 'uint256',
      },
    ],
    name: 'setEARewardsAndLiquidity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_epochManager',
        type: 'address',
      },
    ],
    name: 'setEpochManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'eaId',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'agent',
        type: 'address',
      },
    ],
    name: 'setEvaluationAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: 'uint16',
            name: 'yieldInBps',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'minPrincipalRateInBps',
            type: 'uint16',
          },
          {
            internalType: 'uint96',
            name: 'lateFeeFlat',
            type: 'uint96',
          },
          {
            internalType: 'uint16',
            name: 'lateFeeBps',
            type: 'uint16',
          },
          {
            internalType: 'uint96',
            name: 'membershipFee',
            type: 'uint96',
          },
        ],
        internalType: 'struct FeeStructure',
        name: 'feeStructure',
        type: 'tuple',
      },
    ],
    name: 'setFeeStructure',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint8',
        name: 'index',
        type: 'uint8',
      },
      {
        internalType: 'address',
        name: 'firstLossCover',
        type: 'address',
      },
      {
        internalType: 'uint16',
        name: 'riskYieldMultiplier',
        type: 'uint16',
      },
      {
        internalType: 'address',
        name: 'profitEscrow',
        type: 'address',
      },
    ],
    name: 'setFirstLossCover',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: 'uint96',
            name: 'frontLoadingFeeFlat',
            type: 'uint96',
          },
          {
            internalType: 'uint16',
            name: 'frontLoadingFeeBps',
            type: 'uint16',
          },
        ],
        internalType: 'struct FrontLoadingFeesStructure',
        name: 'frontFees',
        type: 'tuple',
      },
    ],
    name: 'setFrontLoadingFees',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_humaConfig',
        type: 'address',
      },
    ],
    name: 'setHumaConfig',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: 'bool',
            name: 'permissioned',
            type: 'bool',
          },
          {
            internalType: 'uint96',
            name: 'liquidityCap',
            type: 'uint96',
          },
          {
            internalType: 'uint8',
            name: 'withdrawalLockoutInCalendarUnit',
            type: 'uint8',
          },
          {
            internalType: 'uint8',
            name: 'maxSeniorJuniorRatio',
            type: 'uint8',
          },
          {
            internalType: 'uint16',
            name: 'fixedSeniorYieldInBps',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'tranchesRiskAdjustmentInBps',
            type: 'uint16',
          },
        ],
        internalType: 'struct LPConfig',
        name: 'lpConfig',
        type: 'tuple',
      },
    ],
    name: 'setLPConfig',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'gracePeriodInDays',
        type: 'uint256',
      },
    ],
    name: 'setLatePaymentGracePeriodInDays',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'creditLine',
        type: 'uint256',
      },
    ],
    name: 'setMaxCreditLine',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_pool',
        type: 'address',
      },
    ],
    name: 'setPool',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'enum CalendarUnit',
        name: 'unit',
        type: 'uint8',
      },
      {
        internalType: 'uint256',
        name: 'gracePeriod',
        type: 'uint256',
      },
    ],
    name: 'setPoolDefaultGracePeriod',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_poolFeeManager',
        type: 'address',
      },
    ],
    name: 'setPoolFeeManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bool',
        name: 'enabled',
        type: 'bool',
      },
      {
        internalType: 'uint256',
        name: 'windowInEpoch',
        type: 'uint256',
      },
    ],
    name: 'setPoolFlexCall',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'liquidityCap',
        type: 'uint256',
      },
    ],
    name: 'setPoolLiquidityCap',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'newName',
        type: 'string',
      },
    ],
    name: 'setPoolName',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'rewardsRate',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'liquidityRate',
        type: 'uint256',
      },
    ],
    name: 'setPoolOwnerRewardsAndLiquidity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_poolOwnerTreasury',
        type: 'address',
      },
    ],
    name: 'setPoolOwnerTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'enum CalendarUnit',
        name: 'unit',
        type: 'uint8',
      },
      {
        internalType: 'uint256',
        name: 'number',
        type: 'uint256',
      },
    ],
    name: 'setPoolPayPeriod',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_poolSafe',
        type: 'address',
      },
    ],
    name: 'setPoolSafe',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_underlyingToken',
        type: 'address',
      },
    ],
    name: 'setPoolUnderlyingToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_receivableAsset',
        type: 'address',
      },
    ],
    name: 'setReceivableAsset',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'receivableRequiredInBps',
        type: 'uint256',
      },
    ],
    name: 'setReceivableRequiredInBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_seniorTranche',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_juniorTranche',
        type: 'address',
      },
    ],
    name: 'setTranches',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_tranchesPolicy',
        type: 'address',
      },
    ],
    name: 'setTranchesPolicy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'enum CalendarUnit',
        name: 'unit',
        type: 'uint8',
      },
      {
        internalType: 'uint256',
        name: 'lockoutPeriod',
        type: 'uint256',
      },
    ],
    name: 'setWithdrawalLockoutPeriod',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_yieldInBps',
        type: 'uint256',
      },
    ],
    name: 'setYield',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes4',
        name: 'interfaceId',
        type: 'bytes4',
      },
    ],
    name: 'supportsInterface',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tranchesPolicy',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'underlyingToken',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export class PoolConfig__factory {
  static readonly abi = _abi
  static createInterface(): PoolConfigInterface {
    return new utils.Interface(_abi) as PoolConfigInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): PoolConfig {
    return new Contract(address, _abi, signerOrProvider) as PoolConfig
  }
}
