import { POOL_NAME, POOL_TYPE } from '../../utils/pool'
import { ARF_PERSONA_KYC_COPY } from '../../v2'
import { SolanaChainEnum } from '../chain'
import { SolanaChainInfo, SolanaPoolsInfo } from '../pool'

export const SOLANA_MAINNET_INFO: SolanaChainInfo = {
  poolProgram: 'EVQ4s1b6N1vmWFDv8PRNc77kufBP8HcrSNWXQAhRsJq9',
  sentinel: 'Huma3jh5pZd1WKKEApB66W5c75vzHfFdRUHM7oMLwdQV',
}

export const SOLANA_MAINNET_METADATA: SolanaPoolsInfo = {
  ArfCreditPool3Months: {
    title: 'Arf - Cross Border Payment Financing',
    poolName: POOL_NAME.ArfCreditPool3Months,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '29cg8D8hKeNxcN4ujoP2hTNB3eDFgYkzYEKggrJqDAsd',
    poolAuthority: '6Q4e1GEZEYS4GZJst767NU8Z6NeZoqykqhontcWZ33vS',
    poolUnderlyingTokenAccount: '8ZcgiBPiAxErfe3ZPTyKiWPFBCvNP2JeVgUKnTiiFUAc',
    poolConfig: '8NkJUfNPTn7cRF8Jn1Z84SamRe4NLKWhvQLkbcHpsRXP',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'FaAQ5uEm4Coi6mRZ2PkEobbPBDEWHTP8J3HU4jJQnPjP',
    juniorTrancheMint: '3U4X1vs4vvtadfTf4CNqdHZ3fYwL7ZLbWaTKkXjt4c2S',
    juniorTrancheState: 'UZQspSnnmUprmXKQhNxdbWTMwzqfSgoKZfoTHQPuaXw',
    seniorTrancheMint: '7HpPrzapRiAooyCUverJRZVCgXrtroNsvWspCJLh2Mjh',
    seniorTrancheState: '5zNaDGjFZ2XKN8kSX1Yf9LFUToFsd78eK1Um58wa38ZL',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPool6Months: {
    title: 'Arf - Cross Border Payment Financing',
    poolName: POOL_NAME.ArfCreditPool6Months,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '6oAuPDYheeDBrmRgY5z1iXvmFwbmtpEGdGBtMCWgAHwb',
    poolAuthority: 'FyBd4A7VzeTBP1dyfmmi1rqZYx6wpLT63xKKzngDKu5p',
    poolUnderlyingTokenAccount: 'FwZoHpBs1cwHRZzQ9XAzd2Jai4okVVAsNTZbAoEysRpV',
    poolConfig: '4beixqv1temogHLmJU98SLpQvGyxkgTyn2AK7dWTr3k8',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'BA1nPxHMnaWiuXeqHSGQntNnx7hobXhHNtiK1PWhrS6E',
    juniorTrancheMint: 'EabTCfsZytPd8PRAsSVxcPpMn9hPARLFgvNx6eRjFz1i',
    juniorTrancheState: '78Jz2ne15ahye3iC2vVmWF4kDQba7xFFcVE3nT9nE1q6',
    seniorTrancheMint: '9J7t9Lnd3bwmACix1Xiw9W3crdtzx6q5Y18LGt25UYco',
    seniorTrancheState: 'GGsYvQW5Xw4VLwJAzRA36NHFc146XBQJ6DveR2qBAUgS',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  Arf3MonthsCampaign2: {
    title: 'Arf - Cross Border Payment Financing (Campaign II)',
    poolName: POOL_NAME.Arf3MonthsCampaign2,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '38kNbzrKqpkTvRvjAx8HywTaJwtxDDsFQ3fKCLYdXCPM',
    poolAuthority: '7zM9843hUpK7fmL5p58Z939DTiUqg1dpvnocb2D4WcBN',
    poolUnderlyingTokenAccount: 'EuN1J9KGmMJeZP9f3zwffrSTFtmmLSVcHYUsYT22aVRg',
    poolConfig: 'G96PDMMp5A8XgEwiG9qWpqY9mzKAsXxmP7Ums559nhjG',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'J3GVDfNECdNbakVuCcRqUTRoyqei3kwqH9ahdRLFEQoD',
    juniorTrancheMint: '915kNJgdLkM4oAn5Wi6G833cv28Dd9RapsNFsYKpdYPq',
    juniorTrancheState: 'H49HdGY3oGz9J2mjkh5PxcbYvYJ3MbVFGhiYVbwG8UK2',
    seniorTrancheMint: 'kk9sDNbQ89Md6qn7F2MNDtDz2N5UkK3EyFX74JgCJV9',
    seniorTrancheState: 'CTGJ62RoXgCTuChttqcFhT9cg2xb8crS9FwEryA5z1dL',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  Arf6MonthsCampaign2: {
    title: 'Arf - Cross Border Payment Financing (Campaign II)',
    poolName: POOL_NAME.Arf6MonthsCampaign2,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'EwtX42imnenYjLn84RmQ2rSo8TFuRs7E9s4E2ZqVdaFq',
    poolAuthority: 'HKqjZusv2tYgdBBBYSLYhHYimzJzZxbemCMGi1HbzP9K',
    poolUnderlyingTokenAccount: 'GModPwsrSQZCnwzChM7veoe5pj3g8wyQrP9KYbWMtGs9',
    poolConfig: '3wH1HuP3ukKKyDf8urNRg1ikuY4oKxKE1Hq7ZQjxFDDS',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'BpzbLQNxaCDTTH7wdbq7gDqTLiUQFJS79rqVKe1CoKdd',
    juniorTrancheMint: '59c6qYpGQPzLM1DKTKr1Y34MhwCmpVQXC5NYhKR7Rg8v',
    juniorTrancheState: 'EJptJCgqa67TFktLurRks2qbHq8FYVRV35s9nrethysb',
    seniorTrancheMint: 'BYCqSZ3vce2gVKe7vnfZGkuVeibKvsw6xg7gibXd6LUR',
    seniorTrancheState: '4dbBf8BAWfDmU298ia82r6GPMrK4b5J6z4NabnaBLGvT',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
}
