import { POOL_NAME, POOL_TYPE } from '../../utils/pool'
import { ARF_PERSONA_KYC_COPY } from '../../v2'
import { SolanaChainEnum } from '../chain'
import {
  SolanaChainInfo,
  SolanaChainInfoPermissionless,
  SolanaPoolsInfo,
} from '../pool'

export const SOLANA_MAINNET_PERMISSIONLESS: SolanaChainInfoPermissionless = {
  poolProgram: 'HumaXepHnjaRCpjYTokxY4UtaJcmx41prQ8cxGmFC5fn',
  humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
  poolConfig: '28hFhD21Nka3stL27a8zZ4nRLgaDVxRYwJgeEVgeakzS',
  poolState: 'iFgP2EbzHUZzMjqbjaagJQ8zmn6as3Hw95aVUKm67od',
  classicModeConfig: '3FhoMDyKzQqxtGxnz9DfysfoGQKvgDnSFjoDGgguDCQN',
  classicModeMint: '59obFNBzyTBGowrkif5uK7ojS58vsuWz3ZCvg6tfZAGw',
  maxiModeConfig: 'AcHvC47rpoMAY22CbHRpp7vsAskRyhyZGYQCqdm4BWcH',
  maxiModeMint: 'HUPfpnsaJtJGpJxAPNX1vXah7BgYiQYt1c2JMgMumvPs',
  underlyingMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
}

export const SOLANA_MAINNET_INFO: SolanaChainInfo = {
  poolProgram: 'EVQ4s1b6N1vmWFDv8PRNc77kufBP8HcrSNWXQAhRsJq9',
  sentinel: 'Huma3jh5pZd1WKKEApB66W5c75vzHfFdRUHM7oMLwdQV',
}

export const SOLANA_MAINNET_METADATA: SolanaPoolsInfo = {
  ArfCreditPool3Months: {
    title: 'Arf - Cross Border Payment Financing',
    poolName: POOL_NAME.ArfCreditPool3Months,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '29cg8D8hKeNxcN4ujoP2hTNB3eDFgYkzYEKggrJqDAsd',
    poolAuthority: '6Q4e1GEZEYS4GZJst767NU8Z6NeZoqykqhontcWZ33vS',
    poolUnderlyingTokenAccount: '8ZcgiBPiAxErfe3ZPTyKiWPFBCvNP2JeVgUKnTiiFUAc',
    poolConfig: '8NkJUfNPTn7cRF8Jn1Z84SamRe4NLKWhvQLkbcHpsRXP',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'FaAQ5uEm4Coi6mRZ2PkEobbPBDEWHTP8J3HU4jJQnPjP',
    juniorTrancheMint: '3U4X1vs4vvtadfTf4CNqdHZ3fYwL7ZLbWaTKkXjt4c2S',
    juniorTrancheState: 'UZQspSnnmUprmXKQhNxdbWTMwzqfSgoKZfoTHQPuaXw',
    seniorTrancheMint: '7HpPrzapRiAooyCUverJRZVCgXrtroNsvWspCJLh2Mjh',
    seniorTrancheState: '5zNaDGjFZ2XKN8kSX1Yf9LFUToFsd78eK1Um58wa38ZL',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPool6Months: {
    title: 'Arf - Cross Border Payment Financing',
    poolName: POOL_NAME.ArfCreditPool6Months,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '6oAuPDYheeDBrmRgY5z1iXvmFwbmtpEGdGBtMCWgAHwb',
    poolAuthority: 'FyBd4A7VzeTBP1dyfmmi1rqZYx6wpLT63xKKzngDKu5p',
    poolUnderlyingTokenAccount: 'FwZoHpBs1cwHRZzQ9XAzd2Jai4okVVAsNTZbAoEysRpV',
    poolConfig: '4beixqv1temogHLmJU98SLpQvGyxkgTyn2AK7dWTr3k8',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'BA1nPxHMnaWiuXeqHSGQntNnx7hobXhHNtiK1PWhrS6E',
    juniorTrancheMint: 'EabTCfsZytPd8PRAsSVxcPpMn9hPARLFgvNx6eRjFz1i',
    juniorTrancheState: '78Jz2ne15ahye3iC2vVmWF4kDQba7xFFcVE3nT9nE1q6',
    seniorTrancheMint: '9J7t9Lnd3bwmACix1Xiw9W3crdtzx6q5Y18LGt25UYco',
    seniorTrancheState: 'GGsYvQW5Xw4VLwJAzRA36NHFc146XBQJ6DveR2qBAUgS',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPool3MonthsCampaign2: {
    title: 'Arf - Cross Border Payment Financing (Campaign II)',
    poolName: POOL_NAME.ArfCreditPool3MonthsCampaign2,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '38kNbzrKqpkTvRvjAx8HywTaJwtxDDsFQ3fKCLYdXCPM',
    poolAuthority: '7zM9843hUpK7fmL5p58Z939DTiUqg1dpvnocb2D4WcBN',
    poolUnderlyingTokenAccount: 'EuN1J9KGmMJeZP9f3zwffrSTFtmmLSVcHYUsYT22aVRg',
    poolConfig: 'G96PDMMp5A8XgEwiG9qWpqY9mzKAsXxmP7Ums559nhjG',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'J3GVDfNECdNbakVuCcRqUTRoyqei3kwqH9ahdRLFEQoD',
    juniorTrancheMint: '915kNJgdLkM4oAn5Wi6G833cv28Dd9RapsNFsYKpdYPq',
    juniorTrancheState: 'H49HdGY3oGz9J2mjkh5PxcbYvYJ3MbVFGhiYVbwG8UK2',
    seniorTrancheMint: 'kk9sDNbQ89Md6qn7F2MNDtDz2N5UkK3EyFX74JgCJV9',
    seniorTrancheState: 'CTGJ62RoXgCTuChttqcFhT9cg2xb8crS9FwEryA5z1dL',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPool6MonthsCampaign2: {
    title: 'Arf - Cross Border Payment Financing (Campaign II)',
    poolName: POOL_NAME.ArfCreditPool6MonthsCampaign2,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'EwtX42imnenYjLn84RmQ2rSo8TFuRs7E9s4E2ZqVdaFq',
    poolAuthority: 'HKqjZusv2tYgdBBBYSLYhHYimzJzZxbemCMGi1HbzP9K',
    poolUnderlyingTokenAccount: 'GModPwsrSQZCnwzChM7veoe5pj3g8wyQrP9KYbWMtGs9',
    poolConfig: '3wH1HuP3ukKKyDf8urNRg1ikuY4oKxKE1Hq7ZQjxFDDS',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'BpzbLQNxaCDTTH7wdbq7gDqTLiUQFJS79rqVKe1CoKdd',
    juniorTrancheMint: '59c6qYpGQPzLM1DKTKr1Y34MhwCmpVQXC5NYhKR7Rg8v',
    juniorTrancheState: 'EJptJCgqa67TFktLurRks2qbHq8FYVRV35s9nrethysb',
    seniorTrancheMint: 'BYCqSZ3vce2gVKe7vnfZGkuVeibKvsw6xg7gibXd6LUR',
    seniorTrancheState: '4dbBf8BAWfDmU298ia82r6GPMrK4b5J6z4NabnaBLGvT',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPool3MonthsCampaign3: {
    title: 'Arf - Cross Border Payment Financing (Campaign III)',
    poolName: POOL_NAME.ArfCreditPool3MonthsCampaign3,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '3nHRZ5aTYCtAVZiox6hxebvVMy5HSxrjwUaAsKRUs86E',
    poolAuthority: 'CPz13yggA2r4uuWaqnf9vMZFSuT1ZRvwuC6HYEp65dZj',
    poolUnderlyingTokenAccount: 'GXSj53Ajo7o96QJZtnemrDdYjP3ge1aJ2iQXrTUpGBYX',
    poolConfig: '9Qm3Msx5ZeTiaRkNd7XyfdNCNPVhmokufLDiRYFr5fuv',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'D1j3MVtvmfrZ9uFeRSiLzHKSEmH6xzVYToH9Kvju4zCk',
    juniorTrancheMint: 'GY2zqG4y9rQsvXQQ7vLUAT1WREuj2FMsGfdGGe78sgH1',
    juniorTrancheState: '4M1sfTtQieKp3adEPgojcZxs6Abzpthsn26q4fB5WoNH',
    seniorTrancheMint: '75LicBVdQKivDqgGzMBtSGBQhxQNcR5wAtLTd3XAD6r3',
    seniorTrancheState: '4RjUnQJmFL6k2EJA5BXWFANWABdVRNXrTi5Za5DCLF98',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPool6MonthsCampaign3: {
    title: 'Arf - Cross Border Payment Financing (Campaign III)',
    poolName: POOL_NAME.ArfCreditPool6MonthsCampaign3,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: '4dAj7hHg3x9dKXdsAfhfGcGw1XgjGbd6Euzgrujmqnvx',
    poolAuthority: '9KFEW1C2dGX4AjWkhhSpEfJDNccevY5cTrL9H7trrfjX',
    poolUnderlyingTokenAccount: 'BwdUVGe9KBeYryhGMdFWBcqm7T3R3Lm5ZXcxVZZeogJU',
    poolConfig: '2bmDWEKEyL48AugF6rJY5CteY6EaUpVxQGYsDKdCmBF6',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: '35UTpvu1rnAphnsTGo1EPvv6hj2QFZ7HykzUKKLYadd7',
    juniorTrancheMint: 'AryU1pT1x5G3qMAHzeTBVypGs7EJStiPPvL6meFMHmbw',
    juniorTrancheState: '7kqW6EkNpRU83UFv7RRiecnYSfkNBUtjJx8AfhQKe4FD',
    seniorTrancheMint: 'FRWiSbvF1TAH2Pm3zBpXqrkFUikNnZwqvMTJcrvadvHH',
    seniorTrancheState: 'Sm3gFhjpTxjjsET1TzBGWKS9kMYUxh9B5MBKGAzCACH',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPoolApr2025: {
    title: 'Arf - Cross Border Payment Financing (April 2025)',
    poolName: POOL_NAME.ArfCreditPoolApr2025,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'BeXtjb8aERZ1GZXtuEVYCdCXujRriMqqRa26mn8fTvBG',
    poolAuthority: '4SycRpyZbM6pyvEpw1bZFgXoBnGpUMQrp1RGjPbcNniY',
    poolUnderlyingTokenAccount: '8t7L3Qx7hmXg6ch1cbz5Bi8pZs96BL6pNbNFeFfC2S7G',
    poolConfig: 'HrSxoAGb4PH22KuCDzKQo2xkZ7NvUCm3ottDM39BcVni',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'BGR1GWULRi1Bz63WXfAwMnDTKusQyp7eXzLHk3BGTrWx',
    juniorTrancheMint: '4oV6ER2Q69aFSuy8gWDC8yurDeUiknKSidf7TUGLos81',
    juniorTrancheState: '34HXnQqV9d1WKjCMCafPt4yysVoTfe2xUuQ6Kh8RdY3W',
    seniorTrancheMint: 'FqVM58La5X97FpWUhtq1fMgPvUi1KkwQ6RPHc8xzsyeM',
    seniorTrancheState: 'GATHKLhr4Mn7svAmxDDFYSnJURxC9HreA1uRzC4Li3sh',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
    },
  },
  ArfCreditPoolJul2025: {
    title: 'Arf - Cross Border Payment Financing (July 2025)',
    poolName: POOL_NAME.ArfCreditPoolJul2025,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'GNXRzA4jpKbcN1ypWMvW2XLfFMMiFaF1WsmuhSiD8MFT',
    poolAuthority: '6es1yd5V3oWrgPBrPH3UzUM97VuQgsm5H2YLSajYJooQ',
    poolUnderlyingTokenAccount: 'BFgByh5T5rUttvpjzh94DgKaRtp5Goz6wYvgj1SJgc1r',
    poolConfig: 'BStSQ4ZFzHJGXiijbFK6RN6f7hb6DEsEdzGBDq3BGCbm',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'BQd5NDht1Do3vj4wpzagYDKjE17NuY9vsYkzrjqrpVA7',
    juniorTrancheMint: 'ECaFTSrzsKcKq8ZyeHNgchA1n4WBN6oMNu9QQNztptqQ',
    juniorTrancheState: 'yjPniE1s3AtdJ874zQhViKSB4AJeANm6btuMUU2LNhz',
    seniorTrancheMint: 'Ez3efLbdCQv29oC9JQZNnRfLnzS4N5LFEBtcngJjyM7U',
    seniorTrancheState: '5abq5sz2bnULuGV3QxkX98hDRwY5KuKSVPsu462tBxi3',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
      hidden: true,
    },
  },
  ArfInstitutionalPoolODL: {
    title: 'Arf - Cross Border Payment Financing (ODL)',
    poolName: POOL_NAME.ArfInstitutionalPoolODL,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'FkzV1biHWNXb81YyBagfiLr9v7Q2WRzW9mGa6LuuQYji',
    poolAuthority: '2fvRaLXxyaaG3fsCFGbmJzVzEhtcL58McQCV4XK7dESv',
    poolUnderlyingTokenAccount: 'DBk9WZ6JK78ZBLYvSijMJcT7LUopS5MREjD68ozR9wtC',
    poolConfig: '96tEJ4ThtQyBFzuFrqGZssVEUFoec2wW8LJvXVQDkuzm',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: '4PsdWbdwVMSjKRKM7Z7KUZgnX2ULuQHFp6q1W8Ei4n3w',
    juniorTrancheMint: '8w6yzFwtikP3bvw5Dkmb7frhYA29swKg65UAQ2xkzQ1c',
    juniorTrancheState: '4yWJGURzGo7iuu1b4fxey9uDY4Pkeox3zdSCqBGQNwC9',
    seniorTrancheMint: 'FWmJbMcJ7J3u95NXLAY2EhPpTrg9JpwyDYJrb5XAikZa',
    seniorTrancheState: 'E55ctvWwfAmzB9jQzD1uat3v9953E3HbQEDeG8wtEF8w',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
      hidden: true,
    },
  },
  ArfMarJunSepDec: {
    title: 'Arf - Cross Border Payment Financing (Mar Jun Sep Dec)',
    poolName: POOL_NAME.ArfMarJunSepDec,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'BwbBFzCkTLpgwVYY39zP1odhCBZ4ynAdddNZPmD9z7DN',
    poolAuthority: 'HrTdpX2XYKXxKUcv9Mx1Re2kE3xs9XSvWZjsiWX46XNC',
    poolUnderlyingTokenAccount: '4EGKJknpPHxjtb35v8f6JcJZRTSkJeFAwWwFSr9JZ5db',
    poolConfig: 'G1YSwnHprHBds99VLd7BcZ2844YBPjyWrSJLPFoUbHeA',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'J6Tryv2VkwM3zjH6oWuoC9HdqMGiYoSKYv25stgG8Hj2',
    juniorTrancheMint: 'HDBtzprGqgst89eRUMC2jWwWipv7Pt8eL6ZHEe33kdxv',
    juniorTrancheState: '8DrLYuPzZGk1fGK1X1om7pEw1XAn56U7aYRQXTsSC8ev',
    seniorTrancheMint: 'Bug5aHnMzAczah9ULKM98ogZAfBmCuMJeJk3ako58pjU',
    seniorTrancheState: '635x6qefjAzsaNAhtAmW1Ep5TMEUGEexbTtt5Mwi58E9',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
      hidden: true,
    },
  },
  ArfJanAprJulOct: {
    title: 'Arf - Cross Border Payment Financing (Jan Apr Jul Oct)',
    poolName: POOL_NAME.ArfJanAprJulOct,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'CT3e2RvDKm4BthvmdFv8uYntJrRTDpoVUpJCJvnoryFi',
    poolAuthority: 'JAfWip5pubCnZrVqfsqmJkXqfiRvLjjvs6udZzBn4FRf',
    poolUnderlyingTokenAccount: '9Zvb8PNtMzC2EXVD7vifYmJDTwrPBP3duhpdF94deQ58',
    poolConfig: 'AbnVvafstSSQ53JHoamuWhwN4YWppRKoW47p1wGnxVo9',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: 'AzvegJ2iuyJyCHC4tx2D9nYwCMG8we1s4CDMSYBUFAuc',
    juniorTrancheMint: 'B2S2Th5MesVhyBtWyvSqC5FG2ubPXorQDLwFkH2t6U57',
    juniorTrancheState: '7PaVu9p5WrHKjzjUSM4q5iywSP1Nvg8huio6n8Ry8Xdp',
    seniorTrancheMint: '8jXcvWkkRJQb63URMBSahJKAuqDTvj9NTpy9v7kHg5U8',
    seniorTrancheState: 'G1kkcZgxuAqkUqg19i16psCV3wkuWvAcMfiQZsyJU5Bs',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
      hidden: true,
    },
  },
  ArfFebMayAugNov: {
    title: 'Arf - Cross Border Payment Financing (Feb May Aug Nov)',
    poolName: POOL_NAME.ArfFebMayAugNov,
    poolType: POOL_TYPE.CreditLine,
    chainId: SolanaChainEnum.SolanaMainnet,
    industry: 'Remittance Financing',
    desc: 'Arf provides an innovative on-chain liquidity solution that simplifies cross-border payments by facilitating immediate USDC-based settlements and tokenizing payment orders, enhancing transparency in the process.',
    poolId: 'CGfjDiUaGj9L8g9ycLcLnPLAhjAYF4WL4aLAHwDU1Q4B',
    poolAuthority: 'Ed5vK8Fph2iMfpEL2QfXoA8tbHLWaiWiNL6MWz9tWZpU',
    poolUnderlyingTokenAccount: '78XFYDZ5PVrNJr1FYPjxVhca2MAZp48fJ8xpAupLHqWz',
    poolConfig: '3dwCRPejzeyXNFLwfZLhGftGzrLA8cNmrQw7mkheTVun',
    humaConfig: 'Fh2WKYCJfota6k76gDGnhTELUuhPa7FHQvVza4cE11ja',
    poolState: '9KU7tzbgQoRmSDgCxMExSmA8YDhV9JRguF7uxUfwAmdg',
    juniorTrancheMint: 'D1W6yGMNoBU7oqUgFKDdR81K857DFS9d6aTZ985LmueL',
    juniorTrancheState: '6TFgC63jS41xTDm77btiLFYwyKyjsruiVUUgWLDkAWcC',
    seniorTrancheMint: '5NEoXLFry9KwpTEigitRa8kmAkqaHRcHfwwGH14BZnot',
    seniorTrancheState: 'Fcxi2wU7tfQA8WMWRJ8GEoegzs99CTdGcFye9uaN2T93',
    trancheDecimals: 6,
    underlyingMint: {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      decimals: 6,
      icon: 'USDC',
    },
    KYC: {
      Persona: ARF_PERSONA_KYC_COPY,
    },
    extra: {
      hasReceivables: true,
      hidden: true,
    },
  },
}
