#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "develop" ]; then
  cd ..
  echo "$PWD"
  git submodule update --remote
  git add .
  git commit -m "Update submodule huma-js"
  git push
fi
