#!/usr/bin/env sh
SUPERPROJECT_WORKING_TREE=`git rev-parse --show-superproject-working-tree`

# Set husky path if not in a submodule.
if [[ "$SUPERPROJECT_WORKING_TREE" == "" ]]; then
  . "$(dirname -- "$0")/_/husky.sh"
fi

yarn docs:all && yarn prettier:all &&  yarn lint:all && git add . 
