name: Beta NPM Packages Publishing

on:
  workflow_run:
    workflows: ["Huma Monorepo CI"]
    branches: ["develop"]
    types:
      - completed

jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc

      - name: Configure Git User
        run: |
          git config --global user.email "ci@huma.finance"
          git config --global user.name "humaci"

      - name: Publish packages
        run: |
          yarn lerna:publish:canary --yes
