name: Huma Monorepo CI
on:
  pull_request:
    branches: ["develop", "master"]
    paths-ignore:
      - "**/README.md"
      - "**/netlify.toml"
      - "**/gitleaks.toml"
      - "**/LICENSE"
      - "**/.husky/pre-commit"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint all
        run: yarn lint:all

      - name: Build all
        run: yarn build:all

      - name: Unit tests
        run: yarn test:all

      - name: Check for uncommitted changes
        run: |
          # Check for changes after build/docs
          git diff --exit-code --quiet || { echo "Uncommitted changes detected after build/docs"; exit 1; }
