name: Cypress e2e Dev
on:
  pull_request:
    types: [opened, reopened]
    branches: ["develop"]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: e2e-testing-dev

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/huma-dapp
          wait-on: https://deploy-preview-${{github.event.pull_request.number}}--dev-app-huma.netlify.app
          wait-on-timeout: 1800
          config: baseUrl=https://deploy-preview-${{github.event.pull_request.number}}--dev-app-huma.netlify.app
          browser: chrome
          headed: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_E2E_TEST_INFURA_GOERLI: ${{ secrets.CYPRESS_E2E_TEST_INFURA_GOERLI }}
          CYPRESS_E2E_TEST_PRIVATE_KEY: ${{ secrets.CYPRESS_E2E_TEST_PRIVATE_KEY }}
          CYPRESS_E2E_TEST_RN_CREATE_BASE_URL: ${{ vars.CYPRESS_E2E_TEST_RN_CREATE_BASE_URL }}
